### ISSUE TITLE
ROS wrapper

### ISSUE THREAD

**Issue by cmakelabs** [yuhaozhang7/NGD-SLAM#3]
Thank you for your efforts, I have noticed that there is `build_ros.sh`, could you please tell if there is a ROS wrapper for this work that is related to this script? If not, How can I integrate this work with an existing ROS wrapper for ORB-SLAM3 like in this [repo](https://github.com/thien94/orb_slam3_ros)

**Comment by yuhaozhang7** [comment]
Hi, I haven't tried it on ROS; that's just the old script from ORB-SLAM3. One extra implementation is the YOLO thread, which is enabled in `System.cc`, including loading the YOLO model. You might need to look at it if you want to make it a ROS node.
