### ISSUE TITLE
自有数据运行

### ISSUE THREAD

**Issue by Double-zh** [yuhaozhang7/NGD-SLAM#4]
非常棒的工作，请问可以公布在自有数据的教程吗

**Comment by yuhaozhang7** [comment]
你好，让自己的数据集和TUM保持一样的格式就行，再根据自己的相机写一个配置文件，类似于`Examples/RGB-D/TUM3.yaml`。需要注意的就是深度图像的尺度问题，因为代码中用到了深度信息的绝对值。
