### ISSUE TITLE
自有数据集运行问题

### ISSUE THREAD

**Issue by zwj1115** [yuhaozhang7/NGD-SLAM#6]
非常好的工作！在运行的时候我出现了一个小问题，在使用rosbag录制完工作包，在播放时有时会出现第一帧丢失的问题，请问对于rosbag录制初始化工作前，对于场景以及操作有什么要求嘛
Input sensor was set to: RGB-D
Loading settings from ./Examples/RGB-D/TUM3.yaml
Camera1.k3 optional parameter does not exist...
	-Loaded camera 1
Camera.newHeight optional parameter does not exist...
Camera.newWidth optional parameter does not exist...
	-Loaded image info
	-Loaded RGB-D calibration
	-Loaded ORB settings
Viewer.imageViewScale optional parameter does not exist...
	-Loaded viewer settings
System.LoadAtlasFromFile optional parameter does not exist...
System.SaveAtlasToFile optional parameter does not exist...
	-Loaded Atlas settings
System.thFarPoints optional parameter does not exist...
	-Loaded misc parameters
----------------------------------
SLAM settings: 
	-Camera 1 parameters (Pinhole): [ 535.4 539.2 320.1 247.6 ]
	-Camera 1 distortion parameters: [  0 0 0 0 ]
	-Original image size: [ 640 , 480 ]
	-Current image size: [ 640 , 480 ]
	-Sequence FPS: 30
	-RGB-D depth map factor: 5000
	-Features per image: 1000
	-ORB scale factor: 1.2
	-ORB number of scales: 8
	-Initial FAST threshold: 20
	-Min FAST threshold: 7

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Initialization of Atlas from scratch 
Creation of new map with id: 0
Creation of new map with last KF id: 0
Seq. Name: 
There are 1 cameras in the atlas
Camera 0 is pinhole
Net use yolo-fastest

-------
Start processing sequence ...
Images in the sequence: 7288

First KF:0; Map init KF:0
New Map created with 9 points
Average processing time of GrabImageRGBD(): 98.2611ms
Frame 0 end
TRACK_REF_KF: Less than 15 matches!!
Fail to track local map!!!!!!!!!!!!!!!
Average processing time of GrabImageRGBD(): 71.4001ms
Frame 1 end
Starting the Viewer
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 0
mnInitialFrameId = 0
1 Frames set to lost
First KF:1; Map init KF:0
New Map created with 10 points
Average processing time of GrabImageRGBD(): 59.5181ms
Frame 2 end
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.0) /home/zwj/opencv/opencv/modules/video/src/lkpyramid.cpp:1257: error: (-215:Assertion failed) (npoints = prevPtsMat.checkVector(2, CV_32F, true)) >= 0 in function 'calc'

已放弃 (核心已转储)

**Comment by yuhaozhang7** [comment]
你好，可能需要尽量保证深度图的尺度与TUM或BONN数据集一致，该项目暂时还没有对其它相机配置进行代码上的调整。

**Comment by zwj1115** [comment]
> 你好，可能需要尽量保证深度图的尺度和格式与TUM或BONN数据集一致，该项目暂时还没有对其它相机配置进行代码上的调整。

好的，十分感谢！
