### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by ZsLeslie** [yuhaozhang7/NGD-SLAM#7]
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.7) /home/leslie/opencv-3.4.7/modules/dnn/src/darknet/darknet_io.cpp:668: error: (-212:Parsing error) Unknown layer type: dropout in function 'ReadDarknetFromCfgStream'
你好，请问这个报错是由于OpenCV版本导致的吗？还是说有其他的什么原因？

**Comment by yuhaozhang7** [comment]
是的，需要OpenCV>=4.4才能使用读取预训练模型的功能。

**Comment by ZsLeslie** [comment]
好的，谢谢
